version: '3.3'
services:

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - LB-1
      - LB-2
      - LB-3
    volumes:
      - ./janus.toml:/etc/janus/janus.toml
      - ./apis:/etc/janus/apis

  LB-1:
    image: rodolpheche/wiremock
    ports:
      - '9089:8080'
    volumes:
      - ./stubs/LB-1:/home/wiremock/mappings

  LB-2:
    image: rodolpheche/wiremock
    ports:
      - '9090:8080'
    volumes:
      - ./stubs/LB-2:/home/wiremock/mappings

  LB-3:
    image: rodolpheche/wiremock
    ports:
      - '9091:8080'
    volumes:
      - ./stubs/LB-3:/home/wiremock/mappings
