version: '3.3'
services:

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - service1
      - service2
      - service3
    volumes:
      - ./janus.toml:/etc/janus/janus.toml
      - ./apis:/etc/janus/apis

  service1:
    image: rodolpheche/wiremock
    ports:
      - '9089:8080'
    volumes:
      - ./stubs:/home/wiremock/mappings

  service2:
    image: rodolpheche/wiremock
    ports:
      - '9090:8080'
    volumes:
      - ./stubs:/home/wiremock/mappings

  service3:
    image: rodolpheche/wiremock
    ports:
      - '9091:8080'
    volumes:
      - ./stubs:/home/wiremock/mappings
