version: '3.3'
services:

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - service1
    volumes:
      - ./janus.toml:/etc/janus/janus.toml
      - ./apis:/etc/janus/apis

  service1:
    image: rodolpheche/wiremock
    ports:
      - '9089:8080'
    volumes:
      - ./stubs:/home/wiremock/mappings
