version: '3.3'
services:

  api-gateway:
    image:  api-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - service1
      - service2
      - auth-service
    volumes:
      - ./janus.toml:/etc/janus/janus.toml
      - ./apis:/etc/janus/apis
      - ./auth:/etc/janus/auth

  service1:
    image: rodolpheche/wiremock
    ports:
      - '9089:8080'
    volumes:
      - ./stubs/service1:/home/wiremock/mappings

  service2:
    image: rodolpheche/wiremock
    ports:
      - '9090:8080'
    volumes:
      - ./stubs/service2:/home/wiremock/mappings

  auth-service:
    image: rodolpheche/wiremock
    ports:
      - '9088:8080'
    volumes:
      - ./stubs/auth:/home/wiremock/mappings
